FROM golang:alpine AS build

WORKDIR /
COPY grpc grpc
COPY util util
COPY go.* ./
RUN	go build -ldflags="-s -w" -o bin/upload grpc/services/upload/main.go

FROM alpine

COPY --from=build /bin/upload /bin/upload

ENTRYPOINT ["/bin/upload", "-listen_port", ":8080"]
