FROM golang:alpine AS build

WORKDIR /
COPY restful restful
COPY grpc/protos grpc/protos
COPY util util
COPY go.* ./
RUN	go build -ldflags="-s -w" -o bin/server restful/cmd/main.go

FROM scratch

COPY --from=build /bin/server /bin/server

ENTRYPOINT ["/bin/server", "-download_backend_address", "redroc-download-wcsrlqsv2a-uc.a.run.app:443", "-upload_backend_address", "redroc-upload-wcsrlqsv2a-uc.a.run.app:443", "-search_backend_address", "redroc-search-wcsrlqsv2a-uc.a.run.app:443"]
