FROM golang:1.21.0 as build

WORKDIR /
COPY grpc grpc
COPY util util
COPY go.* ./
RUN	CGO_ENABLED=0 go build -ldflags="-s -w" -o bin/search grpc/services/search/main.go

FROM gcr.io/distroless/static-debian11

COPY --from=build /bin/search /bin/search

ENTRYPOINT ["/bin/search", "-listen_port", ":8080"]
