FROM rust:1.73-slim-bullseye AS builder

RUN apt update -y && apt install protobuf-compiler -y
WORKDIR /app
COPY ./apps/server-rs ./apps/server-rs
COPY ./libs ./libs
COPY ./build.rs ./
COPY ./Cargo.toml ./
COPY ./Cargo.lock ./

RUN	cargo build --release

FROM gcr.io/distroless/cc
COPY --from=builder /app/target/release/server /bin/server

ENTRYPOINT ["/bin/server"]
