FROM rust:1.73-slim-bullseye AS build

WORKDIR /
COPY ./apps/server-rs ./apps/server-rs
COPY ./libs ./libs
COPY ./build.rs ./
COPY ./Cargo.toml ./
COPY ./Cargo.lock ./

RUN	cargo build --release

FROM gcr.io/distroless/static-debian11

COPY --from=build /target/release/server /bin/server

ENTRYPOINT ["/bin/server"]
