FROM golang:1.21.0-bullseye as build

WORKDIR /
COPY grpc grpc
COPY .env .env
COPY util util
COPY go.* ./
RUN	CGO_ENABLED=0 go build -ldflags="-s -w" -o bin/download grpc/services/download/main.go

FROM gcr.io/distroless/static-debian11

COPY --from=build /bin/download /bin/download
COPY --from=build .env .env

ENTRYPOINT ["/bin/download", "-listen_port", "8080"]
