FROM golang:1.21-bullseye as build

WORKDIR /
COPY ./apps/download ./
COPY ./libs ./libs

# Set the release variable at build time
ARG RELEASE_ARG
ENV RELEASE=$RELEASE_ARG

RUN	CGO_ENABLED=0 go build -ldflags="-s -w -X main.release=$RELEASE" -o bin/download main.go

FROM gcr.io/distroless/static-debian11

COPY --from=build /bin/download /bin/download
COPY --from=build /.env /.env

ENTRYPOINT ["/bin/download", "-listen_port", "8080"]
