FROM golang:alpine AS build

WORKDIR /
COPY grpc grpc
COPY util util
COPY go.* ./
RUN	go build -ldflags="-s -w" -o bin/download grpc/services/download/main.go

FROM alpine

COPY --from=build /bin/download /bin/download

ENTRYPOINT ["/bin/download"]
