version: "3.8"
services:
  # this database for connecting local
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: redroc
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  # this database for integration test
  postgres-test:
    image: postgres:16
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: template1
    ports:
      - 5433:5432
volumes:
  postgres:
